version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3-stretch-node
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: "Build Revolve's Docker image"
          command: docker build -t cigroup/revolve:$CIRCLE_BRANCH .

      - run:
          name: "Run Python tests"
          command: |
            docker run cigroup/revolve:$CIRCLE_BRANCH ./docker/test_python.sh

      - run:
          name: "Save Revolve's Docker image"
          command: |
            set -e
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push cigroup/revolve:$CIRCLE_BRANCH
